In [1]:
# numpy: array indexing

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[8]

8

In [5]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
slice_arr = arr[0:5]
slice_arr

array([0, 1, 2, 3, 4])

In [10]:
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99, 99])

In [11]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [12]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [13]:
arr_copy[0:5] = 100
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [14]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [15]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr_2d[0][0]

1

In [17]:
arr_2d[1]

array([4, 5, 6])

In [18]:
arr_2d[2,1]

8

In [19]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [20]:
arr_2d[:2,]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
new_arr = np.arange(1,11)
new_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
bool_arr = new_arr > 5
bool_arr 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [23]:
bool_arr.dtype

dtype('bool')

In [24]:
new_arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [25]:
new_arr[new_arr < 6]

array([1, 2, 3, 4, 5])

In [26]:
arr_2d = np.arange(0,50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [27]:
arr_2d[1:3,3:6]

array([[13, 14, 15],
       [23, 24, 25]])