In [1]:
# numpy: array, arange, zeros, ones, linspace, eye, 
#        random (randn, randint), 
#        max, min, argmax, argmin
#        shape, reshape, dtype

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
my_mat = [[1, 2, 3],[1, 2, 3],[1, 2, 3]]
my_mat

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros((3))

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((4))

array([1., 1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [14]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(4,5)

array([[0.63423474, 0.4326211 , 0.92043638, 0.15439755, 0.3889862 ],
       [0.14844305, 0.7319825 , 0.43166348, 0.22529549, 0.50352323],
       [0.81788365, 0.25059064, 0.0305732 , 0.15883786, 0.50603153],
       [0.90639233, 0.09503062, 0.606497  , 0.71831014, 0.0954492 ]])

In [17]:
np.random.randn(3)

array([ 0.82363126, -1.62954165, -0.94396113])

In [18]:
np.random.randn(4,3)

array([[-0.80480711,  0.22298494,  0.42687741],
       [ 0.709617  , -2.3355935 , -0.41379658],
       [ 0.18316239, -0.80670991, -0.68778672],
       [ 0.5499991 , -0.15099703, -0.35760953]])

In [19]:
np.random.randint(5,10)

6

In [20]:
np.random.randint(5,10,6)

array([5, 7, 9, 6, 7, 6])

In [21]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
randarr = np.random.randint(0,25,10)
randarr

array([ 8,  9, 10,  4, 17,  0, 15, 20, 23,  0])

In [24]:
randarr.max()

23

In [25]:
randarr.min()

0

In [26]:
randarr.argmax()

8

In [27]:
randarr.argmin()

5

In [28]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
arr.shape

(20,)

In [30]:
reshapearr = arr.reshape(5,4)
reshapearr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [31]:
reshapearr.shape

(5, 4)

In [32]:
arr.dtype

dtype('int32')

In [33]:
from numpy.random import randint as rt

In [34]:
rt(2,5)

3