In [1]:
# numpy: exercise

In [2]:
# import numpy
import numpy as np

In [3]:
# create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# create an array of 10 fives
np.ones(10) + 4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
# create an array from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
# create an array of 3*3 matrix from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# use numpy to genarate a random number between 0 to 1
np.random.rand(1)

array([0.78589943])

In [9]:
# use numpy to genarate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([ 1.55177715, -0.34703478,  1.48960894, -0.79395525, -1.49299963,
       -0.76559195, -0.15255898,  0.01360225,  0.16582488,  0.86022212,
       -0.34718236, -2.15453014,  0.15487131,  0.23888609,  0.56300304,
       -0.18168819,  0.22553974,  1.26637726,  0.12277582, -0.55925289,
        0.90753829,  0.11166272,  0.07760468,  1.43078656,  0.48765374])

In [10]:
# create the following matrix
arr = np.arange(1,101) / 100
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [11]:
# create an array of 20 linierly spaced points between 0 to 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [12]:
# create the following
# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20],
#        [21, 22, 23, 24, 25]])
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
# grab the following from above
# array([[12, 13, 14, 15],
#        [17, 18, 19, 20],
#        [22, 23, 24, 25]])
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
# grab 20 from above
mat[3,4]

20

In [15]:
# grab the following from above
# array([[ 2],
#        [ 7],
#        [12]])
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [16]:
# grab the following from above
# array([21, 22, 23, 24, 25])
mat[4]

array([21, 22, 23, 24, 25])

In [17]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
# grab the sum of from above
np.sum(mat)

325

In [19]:
# grab the standard deviation of from above
np.std(mat)

7.211102550927978

In [20]:
# get the column wise sum from above
mat.sum(axis=0)

array([55, 60, 65, 70, 75])